-- ============================================================
-- COLDLIFE TWIN — ONE FILE DATA DISPLAY REPAIR
-- 1) Rebuilds/repairs demo data
-- 2) Adds complete UI test data
-- 3) Enables fuel + continuous live backend updates
-- Safe to run on the existing ColdLife Supabase project.
-- ============================================================

-- ColdLife Supabase repair + demo seed. Safe to re-run for this hackathon demo.
-- ColdLife Twin — RUN ALL

-- ============================================================
-- ColdLife Twin — Supabase backend schema
-- Run in Supabase Dashboard -> SQL Editor
-- ============================================================

create extension if not exists pgcrypto;

-- ---------- TABLES ----------

create table if not exists public.cold_storages (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  city text not null,
  latitude double precision not null,
  longitude double precision not null,
  capacity_units integer not null default 0 check (capacity_units >= 0),
  current_load_units integer not null default 0 check (current_load_units >= 0),
  target_temp_min_c numeric(5,2) not null default 2,
  target_temp_max_c numeric(5,2) not null default 8,
  status text not null default 'operational'
    check (status in ('operational','warning','offline')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vehicles (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  registration_no text,
  driver_name text,
  vehicle_type text not null default 'reefer_truck',
  status text not null default 'idle'
    check (status in ('idle','in_transit','maintenance','alert','offline')),
  latitude double precision,
  longitude double precision,
  temperature_c numeric(6,2),
  humidity_pct numeric(6,2),
  battery_pct numeric(6,2) check (battery_pct is null or (battery_pct >= 0 and battery_pct <= 100)),
  speed_kmh numeric(7,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shipments (
  id uuid primary key default gen_random_uuid(),
  tracking_code text not null unique,
  product_name text not null,
  batch_no text,
  quantity integer not null default 1 check (quantity > 0),

  origin_storage_id uuid references public.cold_storages(id) on delete set null,
  destination_storage_id uuid references public.cold_storages(id) on delete set null,
  vehicle_id uuid references public.vehicles(id) on delete set null,

  status text not null default 'scheduled'
    check (status in ('scheduled','in_transit','delayed','delivered','quarantined','cancelled')),
  priority text not null default 'normal'
    check (priority in ('normal','high','critical')),

  target_temp_min_c numeric(5,2) not null default 2,
  target_temp_max_c numeric(5,2) not null default 8,
  current_temp_c numeric(6,2),
  current_humidity_pct numeric(6,2),

  survival_score numeric(5,2) not null default 100
    check (survival_score >= 0 and survival_score <= 100),
  risk_level text not null default 'low'
    check (risk_level in ('low','medium','high','critical')),
  recommendation text not null default 'Continue monitoring.',

  latitude double precision,
  longitude double precision,

  started_at timestamptz,
  eta timestamptz,
  delivered_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telemetry (
  id bigint generated by default as identity primary key,
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  vehicle_id uuid references public.vehicles(id) on delete set null,
  recorded_at timestamptz not null default now(),
  temperature_c numeric(6,2) not null,
  humidity_pct numeric(6,2),
  latitude double precision,
  longitude double precision,
  battery_pct numeric(6,2),
  speed_kmh numeric(7,2),
  door_open boolean not null default false
);

create table if not exists public.alerts (
  id uuid primary key default gen_random_uuid(),
  shipment_id uuid references public.shipments(id) on delete cascade,
  vehicle_id uuid references public.vehicles(id) on delete set null,
  severity text not null default 'warning'
    check (severity in ('info','warning','critical')),
  alert_type text not null,
  title text not null,
  message text not null,
  status text not null default 'open'
    check (status in ('open','acknowledged','resolved')),
  recommended_action text,
  created_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  resolved_at timestamptz
);

create table if not exists public.scenarios (
  id uuid primary key default gen_random_uuid(),
  scenario_key text not null unique,
  name text not null,
  description text not null default '',
  shipment_id uuid references public.shipments(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.simulation_ticks (
  id bigint generated by default as identity primary key,
  scenario_id uuid references public.scenarios(id) on delete set null,
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  tick_no integer not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.shipment_actions (
  id uuid primary key default gen_random_uuid(),
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  action text not null
    check (action in ('QUARANTINE','PRIORITIZE','RESUME','MARK_DELIVERED','RESET_MONITORING')),
  notes text,
  actor text not null default 'demo-user',
  created_at timestamptz not null default now()
);

-- ---------- INDEXES ----------

create index if not exists idx_shipments_status on public.shipments(status);
create index if not exists idx_shipments_vehicle on public.shipments(vehicle_id);
create index if not exists idx_telemetry_shipment_recorded
  on public.telemetry(shipment_id, recorded_at desc);
create index if not exists idx_alerts_status_created
  on public.alerts(status, created_at desc);
create index if not exists idx_alerts_shipment
  on public.alerts(shipment_id, created_at desc);
create index if not exists idx_sim_ticks_shipment
  on public.simulation_ticks(shipment_id, created_at desc);
create index if not exists idx_shipment_actions_shipment
  on public.shipment_actions(shipment_id, created_at desc);

-- ---------- UPDATED_AT TRIGGER ----------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists cold_storages_set_updated_at on public.cold_storages;
create trigger cold_storages_set_updated_at
before update on public.cold_storages
for each row execute procedure public.set_updated_at();

drop trigger if exists vehicles_set_updated_at on public.vehicles;
create trigger vehicles_set_updated_at
before update on public.vehicles
for each row execute procedure public.set_updated_at();

drop trigger if exists shipments_set_updated_at on public.shipments;
create trigger shipments_set_updated_at
before update on public.shipments
for each row execute procedure public.set_updated_at();

-- ---------- READ VIEWS ----------

create or replace view public.shipment_live_view
with (security_invoker = true)
as
select
  s.*,
  os.code as origin_code,
  os.name as origin_name,
  os.city as origin_city,
  ds.code as destination_code,
  ds.name as destination_name,
  ds.city as destination_city,
  v.code as vehicle_code,
  v.registration_no,
  v.driver_name,
  v.status as vehicle_status,
  (
    select count(*)::int
    from public.alerts a
    where a.shipment_id = s.id
      and a.status = 'open'
  ) as open_alert_count
from public.shipments s
left join public.cold_storages os on os.id = s.origin_storage_id
left join public.cold_storages ds on ds.id = s.destination_storage_id
left join public.vehicles v on v.id = s.vehicle_id;

-- fleet_view uses v.*. If vehicle columns were added by an earlier partial run,
-- CREATE OR REPLACE VIEW can interpret the expanded column order as a rename.
-- Recreate the view cleanly so reruns are safe.
drop view if exists public.fleet_view cascade;

create view public.fleet_view
with (security_invoker = true)
as
select
  v.*,
  s.id as active_shipment_id,
  s.tracking_code as active_tracking_code,
  s.product_name as active_product_name,
  s.survival_score as shipment_survival_score,
  s.risk_level as shipment_risk_level
from public.vehicles v
left join lateral (
  select *
  from public.shipments s2
  where s2.vehicle_id = v.id
    and s2.status in ('scheduled','in_transit','delayed','quarantined')
  order by s2.updated_at desc
  limit 1
) s on true;

-- ---------- RPC: HEALTH ----------

create or replace function public.health_check()
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  select jsonb_build_object(
    'status', 'ok',
    'service', 'coldlife-supabase',
    'database', 'connected',
    'time', now()
  );
$$;

-- ---------- RPC: DASHBOARD ----------

create or replace function public.get_dashboard_data()
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  select jsonb_build_object(
    'summary',
      jsonb_build_object(
        'totalShipments', (select count(*) from public.shipments),
        'activeShipments', (
          select count(*) from public.shipments
          where status in ('scheduled','in_transit','delayed','quarantined')
        ),
        'criticalShipments', (
          select count(*) from public.shipments
          where risk_level = 'critical' or status = 'quarantined'
        ),
        'openAlerts', (
          select count(*) from public.alerts where status = 'open'
        ),
        'fleetActive', (
          select count(*) from public.vehicles where status = 'in_transit'
        ),
        'averageSurvivalScore', (
          select coalesce(round(avg(survival_score), 1), 0)
          from public.shipments
        )
      ),
    'shipments',
      coalesce((
        select jsonb_agg(to_jsonb(x))
        from (
          select *
          from public.shipment_live_view
          order by
            case risk_level
              when 'critical' then 1
              when 'high' then 2
              when 'medium' then 3
              else 4
            end,
            updated_at desc
          limit 8
        ) x
      ), '[]'::jsonb),
    'alerts',
      coalesce((
        select jsonb_agg(to_jsonb(a))
        from (
          select *
          from public.alerts
          order by created_at desc
          limit 8
        ) a
      ), '[]'::jsonb),
    'fleet',
      coalesce((
        select jsonb_agg(to_jsonb(f))
        from (
          select *
          from public.fleet_view
          order by code
        ) f
      ), '[]'::jsonb),
    'coldStorages',
      coalesce((
        select jsonb_agg(to_jsonb(c))
        from (
          select *
          from public.cold_storages
          order by name
        ) c
      ), '[]'::jsonb)
  );
$$;

-- ---------- RPC: CONTROLLED SHIPMENT ACTIONS ----------
-- Allows a public hackathon demo to perform a limited set of actions
-- without granting direct UPDATE permission on shipments.

create or replace function public.perform_shipment_action(
  p_shipment_id uuid,
  p_action text,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_action text := upper(trim(p_action));
  v_row public.shipments%rowtype;
begin
  if v_action not in ('QUARANTINE','PRIORITIZE','RESUME','MARK_DELIVERED','RESET_MONITORING') then
    raise exception 'Unsupported shipment action: %', p_action;
  end if;

  if v_action = 'QUARANTINE' then
    update public.shipments
    set status = 'quarantined',
        risk_level = 'critical',
        recommendation = 'Hold shipment for trained quality review before release.'
    where id = p_shipment_id;

  elsif v_action = 'PRIORITIZE' then
    update public.shipments
    set priority = 'critical',
        recommendation = 'Prioritize route and receiving handoff; continue continuous monitoring.'
    where id = p_shipment_id;

  elsif v_action = 'RESUME' then
    update public.shipments
    set status = 'in_transit',
        recommendation = 'Transport resumed. Continue enhanced temperature monitoring.'
    where id = p_shipment_id;

  elsif v_action = 'MARK_DELIVERED' then
    update public.shipments
    set status = 'delivered',
        delivered_at = now(),
        recommendation = 'Shipment delivered. Complete receiving quality checks.'
    where id = p_shipment_id;

  elsif v_action = 'RESET_MONITORING' then
    update public.shipments
    set risk_level = 'low',
        recommendation = 'Continue monitoring.'
    where id = p_shipment_id;

    update public.alerts
    set status = 'resolved',
        resolved_at = now()
    where shipment_id = p_shipment_id
      and status <> 'resolved';
  end if;

  if not found then
    raise exception 'Shipment not found';
  end if;

  insert into public.shipment_actions(shipment_id, action, notes)
  values (p_shipment_id, v_action, p_notes);

  select * into v_row from public.shipments where id = p_shipment_id;

  return jsonb_build_object(
    'ok', true,
    'action', v_action,
    'shipment', to_jsonb(v_row)
  );
end;
$$;

create or replace function public.acknowledge_alert(p_alert_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_alert public.alerts%rowtype;
begin
  update public.alerts
  set status = 'acknowledged',
      acknowledged_at = now()
  where id = p_alert_id
    and status = 'open'
  returning * into v_alert;

  if v_alert.id is null then
    select * into v_alert from public.alerts where id = p_alert_id;
  end if;

  if v_alert.id is null then
    raise exception 'Alert not found';
  end if;

  return jsonb_build_object('ok', true, 'alert', to_jsonb(v_alert));
end;
$$;

-- ---------- RPC: SIMULATION TICK ----------

create or replace function public.run_simulation_tick(p_scenario_key text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_scenario public.scenarios%rowtype;
  v_shipment public.shipments%rowtype;
  v_tick integer;
  v_temp numeric(6,2);
  v_humidity numeric(6,2);
  v_score numeric(5,2);
  v_risk text;
  v_recommendation text;
  v_status text;
  v_payload jsonb;
begin
  select * into v_scenario
  from public.scenarios
  where scenario_key = p_scenario_key
    and is_active = true;

  if v_scenario.id is null then
    raise exception 'Scenario not found: %', p_scenario_key;
  end if;

  select * into v_shipment
  from public.shipments
  where id = v_scenario.shipment_id
  for update;

  if v_shipment.id is null then
    raise exception 'Scenario has no shipment';
  end if;

  select coalesce(max(tick_no), 0) + 1 into v_tick
  from public.simulation_ticks
  where scenario_id = v_scenario.id;

  v_temp := coalesce(v_shipment.current_temp_c, 4.5);
  v_humidity := coalesce(v_shipment.current_humidity_pct, 58);
  v_score := v_shipment.survival_score;
  v_risk := v_shipment.risk_level;
  v_recommendation := v_shipment.recommendation;
  v_status := v_shipment.status;

  if p_scenario_key = 'healthy_delivery' then
    v_temp := greatest(2.5, least(6.0, v_temp + ((random() - 0.5) * 0.5)));
    v_humidity := greatest(45, least(70, v_humidity + ((random() - 0.5) * 2)));
    v_score := least(100, v_score + 0.20);
    v_risk := 'low';
    v_status := 'in_transit';
    v_recommendation := 'Conditions stable. Continue standard monitoring.';

  elsif p_scenario_key = 'recoverable_cooling_failure' then
    if v_tick <= 5 then
      v_temp := least(10.5, v_temp + 0.85);
      v_score := greatest(60, v_score - 2.4);
    else
      v_temp := greatest(5.0, v_temp - 0.95);
      v_score := least(92, v_score + 0.7);
    end if;

    v_humidity := greatest(45, least(78, v_humidity + ((random() - 0.35) * 3)));

    if v_temp > v_shipment.target_temp_max_c then
      v_risk := case when v_temp >= 9.5 then 'high' else 'medium' end;
      v_recommendation := 'Cooling excursion detected. Restore refrigeration and increase monitoring frequency.';

      if not exists (
        select 1 from public.alerts
        where shipment_id = v_shipment.id
          and alert_type = 'cooling_failure'
          and status = 'open'
      ) then
        insert into public.alerts(
          shipment_id, vehicle_id, severity, alert_type, title, message, recommended_action
        ) values (
          v_shipment.id,
          v_shipment.vehicle_id,
          'warning',
          'cooling_failure',
          'Cooling performance degraded',
          'Shipment temperature is above the configured target range.',
          'Restore cooling and review recent telemetry.'
        );
      end if;
    else
      v_risk := 'low';
      v_recommendation := 'Cooling recovered. Continue enhanced monitoring.';
      update public.alerts
      set status = 'resolved', resolved_at = now()
      where shipment_id = v_shipment.id
        and alert_type = 'cooling_failure'
        and status <> 'resolved';
    end if;

  elsif p_scenario_key = 'critical_quarantine' then
    v_temp := least(15.0, v_temp + 1.35);
    v_humidity := least(85, v_humidity + 1.5);
    v_score := greatest(20, v_score - 5.5);
    v_risk := 'critical';
    v_status := 'quarantined';
    v_recommendation := 'Quarantine shipment and require trained quality review before release.';

    if not exists (
      select 1 from public.alerts
      where shipment_id = v_shipment.id
        and alert_type = 'critical_temperature_excursion'
        and status = 'open'
    ) then
      insert into public.alerts(
        shipment_id, vehicle_id, severity, alert_type, title, message, recommended_action
      ) values (
        v_shipment.id,
        v_shipment.vehicle_id,
        'critical',
        'critical_temperature_excursion',
        'Critical cold-chain excursion',
        'Temperature excursion has exceeded the demo critical threshold.',
        'Quarantine and escalate for trained quality review.'
      );
    end if;

  elsif p_scenario_key = 'priority_shipment' then
    v_temp := greatest(3.0, least(6.5, v_temp + ((random() - 0.5) * 0.45)));
    v_humidity := greatest(45, least(70, v_humidity + ((random() - 0.5) * 2)));
    v_score := greatest(88, least(99, v_score + 0.1));
    v_risk := 'low';
    v_status := 'in_transit';
    v_recommendation := 'Priority shipment: maintain expedited route and receiving handoff.';

    update public.shipments
    set priority = 'critical'
    where id = v_shipment.id;
  else
    raise exception 'Scenario handler missing for: %', p_scenario_key;
  end if;

  update public.shipments
  set current_temp_c = round(v_temp, 2),
      current_humidity_pct = round(v_humidity, 2),
      survival_score = round(v_score, 2),
      risk_level = v_risk,
      status = v_status,
      recommendation = v_recommendation,
      latitude = coalesce(latitude, 28.6139) + ((random() - 0.5) * 0.012),
      longitude = coalesce(longitude, 77.2090) + ((random() - 0.5) * 0.012)
  where id = v_shipment.id
  returning * into v_shipment;

  if v_shipment.vehicle_id is not null then
    update public.vehicles
    set temperature_c = v_shipment.current_temp_c,
        humidity_pct = v_shipment.current_humidity_pct,
        latitude = v_shipment.latitude,
        longitude = v_shipment.longitude,
        status = case
          when v_status = 'quarantined' then 'alert'
          when v_status = 'in_transit' then 'in_transit'
          else status
        end
    where id = v_shipment.vehicle_id;
  end if;

  insert into public.telemetry(
    shipment_id, vehicle_id, temperature_c, humidity_pct,
    latitude, longitude, battery_pct, speed_kmh, door_open
  )
  select
    v_shipment.id,
    v_shipment.vehicle_id,
    v_shipment.current_temp_c,
    v_shipment.current_humidity_pct,
    v_shipment.latitude,
    v_shipment.longitude,
    coalesce(v.battery_pct, 90),
    coalesce(v.speed_kmh, 42),
    false
  from public.vehicles v
  where v.id = v_shipment.vehicle_id;

  if v_shipment.vehicle_id is null then
    insert into public.telemetry(
      shipment_id, temperature_c, humidity_pct, latitude, longitude
    ) values (
      v_shipment.id,
      v_shipment.current_temp_c,
      v_shipment.current_humidity_pct,
      v_shipment.latitude,
      v_shipment.longitude
    );
  end if;

  v_payload := jsonb_build_object(
    'scenario', p_scenario_key,
    'tick', v_tick,
    'temperature_c', v_shipment.current_temp_c,
    'humidity_pct', v_shipment.current_humidity_pct,
    'survival_score', v_shipment.survival_score,
    'risk_level', v_shipment.risk_level,
    'status', v_shipment.status,
    'recommendation', v_shipment.recommendation
  );

  insert into public.simulation_ticks(scenario_id, shipment_id, tick_no, payload)
  values (v_scenario.id, v_shipment.id, v_tick, v_payload);

  return jsonb_build_object(
    'ok', true,
    'scenario', p_scenario_key,
    'tick', v_tick,
    'shipment', to_jsonb(v_shipment),
    'payload', v_payload
  );
end;
$$;

-- ---------- RLS ----------
-- This backend is configured for a PUBLIC HACKATHON DEMO:
-- anon/authenticated users can READ operational data.
-- Mutations are limited to controlled RPC functions above.

alter table public.cold_storages enable row level security;
alter table public.vehicles enable row level security;
alter table public.shipments enable row level security;
alter table public.telemetry enable row level security;
alter table public.alerts enable row level security;
alter table public.scenarios enable row level security;
alter table public.simulation_ticks enable row level security;
alter table public.shipment_actions enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array[
    'cold_storages','vehicles','shipments','telemetry',
    'alerts','scenarios','simulation_ticks','shipment_actions'
  ]
  loop
    execute format('drop policy if exists "Public demo read" on public.%I', t);
    execute format(
      'create policy "Public demo read" on public.%I for select to anon, authenticated using (true)',
      t
    );
  end loop;
end $$;

-- Direct writes are intentionally not granted to anon/authenticated.
revoke all on public.cold_storages from anon, authenticated;
revoke all on public.vehicles from anon, authenticated;
revoke all on public.shipments from anon, authenticated;
revoke all on public.telemetry from anon, authenticated;
revoke all on public.alerts from anon, authenticated;
revoke all on public.scenarios from anon, authenticated;
revoke all on public.simulation_ticks from anon, authenticated;
revoke all on public.shipment_actions from anon, authenticated;

grant select on public.cold_storages to anon, authenticated;
grant select on public.vehicles to anon, authenticated;
grant select on public.shipments to anon, authenticated;
grant select on public.telemetry to anon, authenticated;
grant select on public.alerts to anon, authenticated;
grant select on public.scenarios to anon, authenticated;
grant select on public.simulation_ticks to anon, authenticated;
grant select on public.shipment_actions to anon, authenticated;

grant select on public.shipment_live_view to anon, authenticated;
grant select on public.fleet_view to anon, authenticated;

grant execute on function public.health_check() to anon, authenticated;
grant execute on function public.get_dashboard_data() to anon, authenticated;
grant execute on function public.perform_shipment_action(uuid, text, text) to anon, authenticated;
grant execute on function public.acknowledge_alert(uuid) to anon, authenticated;
grant execute on function public.run_simulation_tick(text) to anon, authenticated;

-- ---------- REALTIME ----------

alter table public.shipments replica identity full;
alter table public.vehicles replica identity full;
alter table public.telemetry replica identity full;
alter table public.alerts replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'shipments'
  ) then
    alter publication supabase_realtime add table public.shipments;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'vehicles'
  ) then
    alter publication supabase_realtime add table public.vehicles;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'telemetry'
  ) then
    alter publication supabase_realtime add table public.telemetry;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'alerts'
  ) then
    alter publication supabase_realtime add table public.alerts;
  end if;
end $$;


-- ============================================================
-- ColdLife Twin — demo seed data
-- Run AFTER schema.sql
-- ============================================================

-- Cold storages
insert into public.cold_storages (
  id, code, name, city, latitude, longitude,
  capacity_units, current_load_units,
  target_temp_min_c, target_temp_max_c, status
) values
(
  '10000000-0000-0000-0000-000000000001',
  'DEL-HUB-01', 'Delhi BioCold Hub', 'Delhi',
  28.6139, 77.2090, 15000, 9300, 2, 8, 'operational'
),
(
  '10000000-0000-0000-0000-000000000002',
  'GGN-HUB-01', 'Gurugram Pharma Cold Store', 'Gurugram',
  28.4595, 77.0266, 9000, 5400, 2, 8, 'operational'
),
(
  '10000000-0000-0000-0000-000000000003',
  'NOI-HUB-01', 'Noida Clinical Logistics Hub', 'Noida',
  28.5355, 77.3910, 11000, 7600, 2, 8, 'operational'
)
on conflict (id) do update set
  name = excluded.name,
  current_load_units = excluded.current_load_units,
  status = excluded.status;

-- Vehicles
insert into public.vehicles (
  id, code, registration_no, driver_name, status,
  latitude, longitude, temperature_c, humidity_pct,
  battery_pct, speed_kmh
) values
(
  '20000000-0000-0000-0000-000000000001',
  'CL-REEFER-01', 'DL01CL1001', 'Arjun Mehta', 'in_transit',
  28.5900, 77.2200, 4.2, 58, 92, 43
),
(
  '20000000-0000-0000-0000-000000000002',
  'CL-REEFER-02', 'HR26CL2002', 'Neeraj Singh', 'in_transit',
  28.5200, 77.0900, 6.4, 62, 84, 37
),
(
  '20000000-0000-0000-0000-000000000003',
  'CL-REEFER-03', 'UP16CL3003', 'Riya Sharma', 'alert',
  28.5700, 77.3100, 10.8, 74, 78, 18
),
(
  '20000000-0000-0000-0000-000000000004',
  'CL-REEFER-04', 'DL01CL4004', 'Kabir Malhotra', 'in_transit',
  28.6300, 77.1800, 3.9, 55, 96, 51
)
on conflict (id) do update set
  driver_name = excluded.driver_name,
  status = excluded.status,
  temperature_c = excluded.temperature_c;

-- Shipments
insert into public.shipments (
  id, tracking_code, product_name, batch_no, quantity,
  origin_storage_id, destination_storage_id, vehicle_id,
  status, priority,
  target_temp_min_c, target_temp_max_c,
  current_temp_c, current_humidity_pct,
  survival_score, risk_level, recommendation,
  latitude, longitude, started_at, eta
) values
(
  '30000000-0000-0000-0000-000000000001',
  'CLT-1001', 'Insulin', 'INS-2026-A14', 480,
  '10000000-0000-0000-0000-000000000001',
  '10000000-0000-0000-0000-000000000003',
  '20000000-0000-0000-0000-000000000001',
  'in_transit', 'normal', 2, 8,
  4.2, 58, 98, 'low',
  'Conditions stable. Continue standard monitoring.',
  28.5900, 77.2200, now() - interval '55 minutes', now() + interval '65 minutes'
),
(
  '30000000-0000-0000-0000-000000000002',
  'CLT-1002', 'Temperature-Sensitive Vaccine', 'VAC-2026-B07', 1200,
  '10000000-0000-0000-0000-000000000002',
  '10000000-0000-0000-0000-000000000001',
  '20000000-0000-0000-0000-000000000002',
  'in_transit', 'high', 2, 8,
  6.4, 62, 91, 'medium',
  'Cooling performance requires closer monitoring.',
  28.5200, 77.0900, now() - interval '80 minutes', now() + interval '50 minutes'
),
(
  '30000000-0000-0000-0000-000000000003',
  'CLT-1003', 'Biologic Therapy', 'BIO-2026-C09', 180,
  '10000000-0000-0000-0000-000000000003',
  '10000000-0000-0000-0000-000000000001',
  '20000000-0000-0000-0000-000000000003',
  'quarantined', 'critical', 2, 8,
  10.8, 74, 54, 'critical',
  'Quarantine shipment and require trained quality review before release.',
  28.5700, 77.3100, now() - interval '100 minutes', now() + interval '35 minutes'
),
(
  '30000000-0000-0000-0000-000000000004',
  'CLT-1004', 'Emergency Antivenom', 'ANT-2026-D22', 75,
  '10000000-0000-0000-0000-000000000001',
  '10000000-0000-0000-0000-000000000002',
  '20000000-0000-0000-0000-000000000004',
  'in_transit', 'critical', 2, 8,
  3.9, 55, 97, 'low',
  'Priority shipment: maintain expedited route and receiving handoff.',
  28.6300, 77.1800, now() - interval '30 minutes', now() + interval '40 minutes'
)
on conflict (id) do update set
  current_temp_c = excluded.current_temp_c,
  current_humidity_pct = excluded.current_humidity_pct,
  survival_score = excluded.survival_score,
  risk_level = excluded.risk_level,
  recommendation = excluded.recommendation,
  status = excluded.status,
  priority = excluded.priority;

-- Initial telemetry
insert into public.telemetry (
  shipment_id, vehicle_id, recorded_at, temperature_c,
  humidity_pct, latitude, longitude, battery_pct, speed_kmh, door_open
)
select s.id, s.vehicle_id, now() - interval '10 minutes',
       s.current_temp_c, s.current_humidity_pct,
       s.latitude, s.longitude,
       v.battery_pct, v.speed_kmh, false
from public.shipments s
left join public.vehicles v on v.id = s.vehicle_id
where not exists (
  select 1 from public.telemetry t
  where t.shipment_id = s.id
);

-- Alerts
insert into public.alerts (
  id, shipment_id, vehicle_id, severity, alert_type,
  title, message, status, recommended_action
) values
(
  '40000000-0000-0000-0000-000000000001',
  '30000000-0000-0000-0000-000000000002',
  '20000000-0000-0000-0000-000000000002',
  'warning', 'cooling_failure',
  'Cooling performance degraded',
  'Temperature is trending toward the upper target limit.',
  'open',
  'Restore cooling efficiency and increase monitoring frequency.'
),
(
  '40000000-0000-0000-0000-000000000002',
  '30000000-0000-0000-0000-000000000003',
  '20000000-0000-0000-0000-000000000003',
  'critical', 'critical_temperature_excursion',
  'Critical cold-chain excursion',
  'Shipment is outside the target temperature range and is quarantined.',
  'open',
  'Maintain quarantine and escalate for trained quality review.'
)
on conflict (id) do update set
  status = excluded.status,
  message = excluded.message;

-- Demo scenarios matching the frontend README
insert into public.scenarios (
  id, scenario_key, name, description, shipment_id, is_active
) values
(
  '50000000-0000-0000-0000-000000000001',
  'healthy_delivery',
  'Healthy delivery',
  'Stable temperature, high survival score and normal transport.',
  '30000000-0000-0000-0000-000000000001',
  true
),
(
  '50000000-0000-0000-0000-000000000002',
  'recoverable_cooling_failure',
  'Recoverable cooling failure',
  'Temperature rises temporarily, then recovers after intervention.',
  '30000000-0000-0000-0000-000000000002',
  true
),
(
  '50000000-0000-0000-0000-000000000003',
  'critical_quarantine',
  'Critical quarantine',
  'Critical excursion pushes the shipment into quarantine.',
  '30000000-0000-0000-0000-000000000003',
  true
),
(
  '50000000-0000-0000-0000-000000000004',
  'priority_shipment',
  'Priority shipment',
  'High-priority shipment remains stable while receiving expedited handling.',
  '30000000-0000-0000-0000-000000000004',
  true
)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  shipment_id = excluded.shipment_id,
  is_active = excluded.is_active;

-- ============================================================
-- FULL UI DEMO DATA EXTENSION
-- Adds chain-of-custody, driver behavior, vehicle health,
-- dense telemetry and survival/risk time series.
-- Safe to re-run for the four built-in demo shipments.
-- ============================================================

create table if not exists public.custody_events (
  id uuid primary key default gen_random_uuid(),
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  event_type text not null,
  title text not null,
  description text not null default '',
  location text,
  actor text,
  status text not null default 'complete',
  recorded_at timestamptz not null default now()
);

create table if not exists public.driver_behavior_snapshots (
  id bigint generated by default as identity primary key,
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  vehicle_id uuid references public.vehicles(id) on delete set null,
  driver_name text,
  style text not null default 'balanced',
  driver_score numeric(5,2) not null default 90,
  avg_speed_kmh numeric(7,2),
  max_speed_kmh numeric(7,2),
  harsh_braking_count integer not null default 0,
  harsh_accel_count integer not null default 0,
  cornering_count integer not null default 0,
  speeding_events integer not null default 0,
  idle_minutes numeric(7,2) not null default 0,
  fatigue_score numeric(5,2) not null default 10,
  eco_score numeric(5,2) not null default 90,
  recorded_at timestamptz not null default now()
);

create table if not exists public.vehicle_health_snapshots (
  id bigint generated by default as identity primary key,
  vehicle_id uuid not null references public.vehicles(id) on delete cascade,
  overall_health_pct numeric(5,2) not null default 90,
  reefer_health_pct numeric(5,2) not null default 90,
  compressor_efficiency_pct numeric(5,2) not null default 90,
  battery_health_pct numeric(5,2) not null default 90,
  battery_pct numeric(5,2),
  fuel_pct numeric(5,2),
  engine_temp_c numeric(6,2),
  coolant_pct numeric(5,2),
  tyre_pressure_psi numeric(6,2),
  gps_signal_pct numeric(5,2),
  door_status text not null default 'closed',
  service_due_km integer not null default 2500,
  reefer_runtime_hours numeric(10,2) not null default 0,
  recorded_at timestamptz not null default now()
);

create index if not exists idx_custody_events_shipment_time
  on public.custody_events(shipment_id, recorded_at);
create index if not exists idx_driver_behavior_shipment_time
  on public.driver_behavior_snapshots(shipment_id, recorded_at);
create index if not exists idx_vehicle_health_vehicle_time
  on public.vehicle_health_snapshots(vehicle_id, recorded_at);

alter table public.custody_events enable row level security;
alter table public.driver_behavior_snapshots enable row level security;
alter table public.vehicle_health_snapshots enable row level security;

drop policy if exists "Public demo read" on public.custody_events;
create policy "Public demo read" on public.custody_events
  for select to anon, authenticated using (true);
drop policy if exists "Public demo read" on public.driver_behavior_snapshots;
create policy "Public demo read" on public.driver_behavior_snapshots
  for select to anon, authenticated using (true);
drop policy if exists "Public demo read" on public.vehicle_health_snapshots;
create policy "Public demo read" on public.vehicle_health_snapshots
  for select to anon, authenticated using (true);

grant select on public.custody_events to anon, authenticated;
grant select on public.driver_behavior_snapshots to anon, authenticated;
grant select on public.vehicle_health_snapshots to anon, authenticated;

-- Keep the IDs stable, but align tracking codes with the frontend demo IDs.
update public.shipments set tracking_code = 'CLT-2401' where id = '30000000-0000-0000-0000-000000000001';
update public.shipments set tracking_code = 'CLT-2402' where id = '30000000-0000-0000-0000-000000000002';
update public.shipments set tracking_code = 'CLT-2403' where id = '30000000-0000-0000-0000-000000000003';
update public.shipments set tracking_code = 'CLT-2404' where id = '30000000-0000-0000-0000-000000000004';

-- Final current state for each demo digital twin.
update public.shipments set
  product_name='Insulin Glargine', batch_no='INS-2026-A14', quantity=480,
  status='in_transit', priority='normal', current_temp_c=4.2,
  current_humidity_pct=58, survival_score=98, risk_level='low',
  recommendation='Conditions stable. Continue standard monitoring.',
  latitude=28.5900, longitude=77.2200,
  started_at=now()-interval '2 hours', eta=now()+interval '65 minutes'
where id='30000000-0000-0000-0000-000000000001';

update public.shipments set
  product_name='mRNA Vaccine', batch_no='VAC-2026-B07', quantity=1200,
  status='in_transit', priority='high', current_temp_c=6.4,
  current_humidity_pct=62, survival_score=91, risk_level='medium',
  recommendation='Cooling recovered after intervention. Continue enhanced monitoring.',
  latitude=28.5200, longitude=77.0900,
  started_at=now()-interval '2 hours 20 minutes', eta=now()+interval '50 minutes'
where id='30000000-0000-0000-0000-000000000002';

update public.shipments set
  product_name='Monoclonal Antibody Therapy', batch_no='BIO-2026-C09', quantity=180,
  status='quarantined', priority='critical', current_temp_c=10.8,
  current_humidity_pct=74, survival_score=54, risk_level='critical',
  recommendation='Quarantine shipment and require trained quality review before release.',
  latitude=28.5700, longitude=77.3100,
  started_at=now()-interval '2 hours 50 minutes', eta=now()+interval '35 minutes'
where id='30000000-0000-0000-0000-000000000003';

update public.shipments set
  product_name='Emergency Antivenom', batch_no='ANT-2026-D22', quantity=75,
  status='in_transit', priority='critical', current_temp_c=3.9,
  current_humidity_pct=55, survival_score=97, risk_level='low',
  recommendation='Priority shipment: maintain expedited route and receiving handoff.',
  latitude=28.6300, longitude=77.1800,
  started_at=now()-interval '90 minutes', eta=now()+interval '40 minutes'
where id='30000000-0000-0000-0000-000000000004';

update public.vehicles set
  driver_name='Arjun Mehta', status='in_transit', latitude=28.5900, longitude=77.2200,
  temperature_c=4.2, humidity_pct=58, battery_pct=92, speed_kmh=43
where id='20000000-0000-0000-0000-000000000001';
update public.vehicles set
  driver_name='Neeraj Singh', status='in_transit', latitude=28.5200, longitude=77.0900,
  temperature_c=6.4, humidity_pct=62, battery_pct=84, speed_kmh=37
where id='20000000-0000-0000-0000-000000000002';
update public.vehicles set
  driver_name='Riya Sharma', status='alert', latitude=28.5700, longitude=77.3100,
  temperature_c=10.8, humidity_pct=74, battery_pct=78, speed_kmh=18
where id='20000000-0000-0000-0000-000000000003';
update public.vehicles set
  driver_name='Kabir Malhotra', status='in_transit', latitude=28.6300, longitude=77.1800,
  temperature_c=3.9, humidity_pct=55, battery_pct=96, speed_kmh=51
where id='20000000-0000-0000-0000-000000000004';

-- Rebuild dense graph/test data for only the four demo twins.
delete from public.telemetry
where shipment_id in (
  '30000000-0000-0000-0000-000000000001',
  '30000000-0000-0000-0000-000000000002',
  '30000000-0000-0000-0000-000000000003',
  '30000000-0000-0000-0000-000000000004'
);

delete from public.simulation_ticks
where shipment_id in (
  '30000000-0000-0000-0000-000000000001',
  '30000000-0000-0000-0000-000000000002',
  '30000000-0000-0000-0000-000000000003',
  '30000000-0000-0000-0000-000000000004'
);

delete from public.custody_events
where shipment_id in (
  '30000000-0000-0000-0000-000000000001',
  '30000000-0000-0000-0000-000000000002',
  '30000000-0000-0000-0000-000000000003',
  '30000000-0000-0000-0000-000000000004'
);

delete from public.driver_behavior_snapshots
where shipment_id in (
  '30000000-0000-0000-0000-000000000001',
  '30000000-0000-0000-0000-000000000002',
  '30000000-0000-0000-0000-000000000003',
  '30000000-0000-0000-0000-000000000004'
);

delete from public.vehicle_health_snapshots
where vehicle_id in (
  '20000000-0000-0000-0000-000000000001',
  '20000000-0000-0000-0000-000000000002',
  '20000000-0000-0000-0000-000000000003',
  '20000000-0000-0000-0000-000000000004'
);

-- 24 telemetry points per shipment: enough to render smooth temperature graphs.
insert into public.telemetry (
  shipment_id, vehicle_id, recorded_at, temperature_c, humidity_pct,
  latitude, longitude, battery_pct, speed_kmh, door_open
)
select
  s.id,
  s.vehicle_id,
  now() - ((23-g) * interval '5 minutes'),
  case s.id
    when '30000000-0000-0000-0000-000000000001'::uuid then round((4.05 + ((g % 5)-2)*0.07)::numeric, 2)
    when '30000000-0000-0000-0000-000000000002'::uuid then round((case when g <= 12 then 4.80 + g*0.28 else 8.16 - (g-12)*0.16 end)::numeric, 2)
    when '30000000-0000-0000-0000-000000000003'::uuid then round((4.59 + g*0.27)::numeric, 2)
    else round((3.90 + ((g % 6)-3)*0.06)::numeric, 2)
  end,
  case s.id
    when '30000000-0000-0000-0000-000000000001'::uuid then 56 + (g % 5)
    when '30000000-0000-0000-0000-000000000002'::uuid then 57 + round((g*0.22)::numeric, 1)
    when '30000000-0000-0000-0000-000000000003'::uuid then 61 + round((g*0.57)::numeric, 1)
    else 53 + (g % 4)
  end,
  s.latitude + ((g-23) * 0.0012),
  s.longitude + ((g-23) * 0.0010),
  greatest(35, v.battery_pct + (23-g)*0.22),
  case s.id
    when '30000000-0000-0000-0000-000000000001'::uuid then 34 + (g % 6)*3
    when '30000000-0000-0000-0000-000000000002'::uuid then 28 + (g % 7)*3
    when '30000000-0000-0000-0000-000000000003'::uuid then 15 + (g % 5)*2
    else 42 + (g % 6)*3
  end,
  case when g in (2,3) then true else false end
from public.shipments s
join public.vehicles v on v.id=s.vehicle_id
cross join generate_series(0,23) g
where s.id in (
  '30000000-0000-0000-0000-000000000001',
  '30000000-0000-0000-0000-000000000002',
  '30000000-0000-0000-0000-000000000003',
  '30000000-0000-0000-0000-000000000004'
);

-- 16 survival/risk points per shipment for the risk trajectory graph.
insert into public.simulation_ticks (
  scenario_id, shipment_id, tick_no, payload, created_at
)
select
  sc.id,
  s.id,
  g+1,
  jsonb_build_object(
    'survival_score',
      case s.id
        when '30000000-0000-0000-0000-000000000001'::uuid then round((99.5 - g*0.10)::numeric, 1)
        when '30000000-0000-0000-0000-000000000002'::uuid then round((case when g <= 10 then 99.0 - g*0.90 else 90.0 + (g-10)*0.20 end)::numeric, 1)
        when '30000000-0000-0000-0000-000000000003'::uuid then round((96.0 - g*2.80)::numeric, 1)
        else round((99.0 - g*(2.0/15.0))::numeric, 1)
      end,
    'risk_level',
      case s.id
        when '30000000-0000-0000-0000-000000000003'::uuid then case when g < 6 then 'medium' when g < 11 then 'high' else 'critical' end
        when '30000000-0000-0000-0000-000000000002'::uuid then case when g < 7 then 'low' when g < 13 then 'medium' else 'low' end
        else 'low'
      end,
    'temperature_c',
      case s.id
        when '30000000-0000-0000-0000-000000000001'::uuid then 4.2
        when '30000000-0000-0000-0000-000000000002'::uuid then case when g <= 10 then 4.8 + g*0.34 else 8.2 - (g-10)*0.36 end
        when '30000000-0000-0000-0000-000000000003'::uuid then 4.8 + g*0.40
        else 3.9
      end
  ),
  now() - ((15-g) * interval '7 minutes')
from public.shipments s
left join public.scenarios sc on sc.shipment_id=s.id
cross join generate_series(0,15) g
where s.id in (
  '30000000-0000-0000-0000-000000000001',
  '30000000-0000-0000-0000-000000000002',
  '30000000-0000-0000-0000-000000000003',
  '30000000-0000-0000-0000-000000000004'
);

-- Chain of custody / operational timeline.
insert into public.custody_events (shipment_id,event_type,title,description,location,actor,status,recorded_at) values
('30000000-0000-0000-0000-000000000001','created','Order released','Shipment released by pharmacy distribution control.','Delhi BioCold Hub','Control Tower','complete',now()-interval '135 minutes'),
('30000000-0000-0000-0000-000000000001','loaded','Cold load completed','480 insulin units loaded into validated reefer compartment.','Delhi BioCold Hub','Warehouse Team A','complete',now()-interval '125 minutes'),
('30000000-0000-0000-0000-000000000001','seal_verified','Security seal verified','Electronic seal CL-88401 verified and door closed.','Delhi BioCold Hub','Arjun Mehta','complete',now()-interval '121 minutes'),
('30000000-0000-0000-0000-000000000001','departed','Vehicle departed','Reefer departed within target temperature band.','Delhi Ring Road','Control Tower','complete',now()-interval '115 minutes'),
('30000000-0000-0000-0000-000000000001','checkpoint','Temperature checkpoint passed','Temperature stable at 4.1°C; no intervention required.','Akshardham Corridor','Digital Twin','complete',now()-interval '50 minutes'),
('30000000-0000-0000-0000-000000000001','live','Live monitoring','Shipment remains inside validated range.','Noida Approach','Digital Twin','active',now()-interval '3 minutes'),

('30000000-0000-0000-0000-000000000002','created','Vaccine dispatch created','Priority vaccine movement released for transport.','Gurugram Pharma Cold Store','Control Tower','complete',now()-interval '155 minutes'),
('30000000-0000-0000-0000-000000000002','loaded','Validated load complete','Vaccine cartons loaded with active temperature logger.','Gurugram Pharma Cold Store','Warehouse Team B','complete',now()-interval '145 minutes'),
('30000000-0000-0000-0000-000000000002','departed','Vehicle departed','Route to Delhi receiving hub started.','NH-48','Neeraj Singh','complete',now()-interval '138 minutes'),
('30000000-0000-0000-0000-000000000002','warning','Cooling degradation detected','Supply air temperature started trending toward upper limit.','Mahipalpur','Digital Twin','warning',now()-interval '52 minutes'),
('30000000-0000-0000-0000-000000000002','intervention','Cooling intervention accepted','Driver increased reefer cooling and reduced door exposure.','Dhaula Kuan','Neeraj Singh','complete',now()-interval '38 minutes'),
('30000000-0000-0000-0000-000000000002','recovered','Temperature recovered','Product temperature returned to safe operating band.','Central Delhi','Digital Twin','active',now()-interval '10 minutes'),

('30000000-0000-0000-0000-000000000003','created','Biologic shipment released','High-value biologic shipment released for monitored transit.','Noida Clinical Logistics Hub','Control Tower','complete',now()-interval '185 minutes'),
('30000000-0000-0000-0000-000000000003','loaded','Cold load completed','Biologic therapy loaded and seal verified.','Noida Clinical Logistics Hub','Warehouse Team C','complete',now()-interval '175 minutes'),
('30000000-0000-0000-0000-000000000003','departed','Vehicle departed','Validated route initiated.','Noida Expressway','Riya Sharma','complete',now()-interval '168 minutes'),
('30000000-0000-0000-0000-000000000003','warning','Temperature excursion started','Temperature crossed 8°C target maximum.','Mayur Vihar','Digital Twin','warning',now()-interval '64 minutes'),
('30000000-0000-0000-0000-000000000003','critical','Critical excursion confirmed','Predicted survival fell below release threshold.','East Delhi','Digital Twin','critical',now()-interval '28 minutes'),
('30000000-0000-0000-0000-000000000003','quarantine','Shipment quarantined','Automated recommendation accepted; quality review required.','Delhi Quality Hold Point','Control Tower','critical',now()-interval '18 minutes'),

('30000000-0000-0000-0000-000000000004','created','Emergency order received','Emergency antivenom order created with critical priority.','Delhi BioCold Hub','Emergency Desk','complete',now()-interval '105 minutes'),
('30000000-0000-0000-0000-000000000004','loaded','Expedited loading complete','Antivenom batch loaded and validated.','Delhi BioCold Hub','Warehouse Team A','complete',now()-interval '98 minutes'),
('30000000-0000-0000-0000-000000000004','priority','Priority corridor activated','Traffic-aware priority route activated for emergency delivery.','Central Delhi','Control Tower','complete',now()-interval '80 minutes'),
('30000000-0000-0000-0000-000000000004','checkpoint','Cold chain verified','Temperature stable at 3.9°C and seal intact.','Karol Bagh','Digital Twin','complete',now()-interval '44 minutes'),
('30000000-0000-0000-0000-000000000004','handoff_ready','Receiving team notified','Hospital receiving team notified of accelerated ETA.','Hospital Receiving Bay','Control Tower','active',now()-interval '12 minutes');

-- Driver behaviour snapshots: 8 points per active shipment.
insert into public.driver_behavior_snapshots (
  shipment_id,vehicle_id,driver_name,style,driver_score,avg_speed_kmh,max_speed_kmh,
  harsh_braking_count,harsh_accel_count,cornering_count,speeding_events,idle_minutes,
  fatigue_score,eco_score,recorded_at
)
select
  s.id,s.vehicle_id,v.driver_name,
  case s.id
    when '30000000-0000-0000-0000-000000000001'::uuid then 'balanced'
    when '30000000-0000-0000-0000-000000000002'::uuid then 'smooth'
    when '30000000-0000-0000-0000-000000000003'::uuid then 'cautious'
    else 'brisk'
  end,
  case s.id
    when '30000000-0000-0000-0000-000000000001'::uuid then 94-g*0.4
    when '30000000-0000-0000-0000-000000000002'::uuid then 96-g*0.3
    when '30000000-0000-0000-0000-000000000003'::uuid then 91-g*0.6
    else 89-g*0.5
  end,
  case s.id when '30000000-0000-0000-0000-000000000004'::uuid then 48 else 34+(g%4)*2 end,
  case s.id when '30000000-0000-0000-0000-000000000004'::uuid then 67 else 52+(g%3)*3 end,
  case s.id when '30000000-0000-0000-0000-000000000004'::uuid then 1+(g/4) else (g/6) end,
  case s.id when '30000000-0000-0000-0000-000000000004'::uuid then 2+(g/5) else (g/6) end,
  case s.id when '30000000-0000-0000-0000-000000000003'::uuid then 2+(g/5) else (g/4) end,
  case s.id when '30000000-0000-0000-0000-000000000004'::uuid then 1+(g/5) else 0 end,
  round((2.0 + g*0.7)::numeric,1),
  case s.id when '30000000-0000-0000-0000-000000000003'::uuid then 20+g*1.5 else 9+g*0.8 end,
  case s.id
    when '30000000-0000-0000-0000-000000000001'::uuid then 92-g*0.3
    when '30000000-0000-0000-0000-000000000002'::uuid then 95-g*0.2
    when '30000000-0000-0000-0000-000000000003'::uuid then 86-g*0.5
    else 82-g*0.6
  end,
  now()-((7-g)*interval '15 minutes')
from public.shipments s
join public.vehicles v on v.id=s.vehicle_id
cross join generate_series(0,7) g
where s.id in (
  '30000000-0000-0000-0000-000000000001',
  '30000000-0000-0000-0000-000000000002',
  '30000000-0000-0000-0000-000000000003',
  '30000000-0000-0000-0000-000000000004'
);

-- Vehicle health snapshots: current and historical reefer/vehicle condition.
insert into public.vehicle_health_snapshots (
  vehicle_id,overall_health_pct,reefer_health_pct,compressor_efficiency_pct,battery_health_pct,
  battery_pct,fuel_pct,engine_temp_c,coolant_pct,tyre_pressure_psi,gps_signal_pct,door_status,
  service_due_km,reefer_runtime_hours,recorded_at
)
select
  v.id,
  case v.id
    when '20000000-0000-0000-0000-000000000001'::uuid then 96-g*0.15
    when '20000000-0000-0000-0000-000000000002'::uuid then 87-g*0.35
    when '20000000-0000-0000-0000-000000000003'::uuid then 72-g*0.90
    else 93-g*0.20
  end,
  case v.id
    when '20000000-0000-0000-0000-000000000001'::uuid then 97-g*0.10
    when '20000000-0000-0000-0000-000000000002'::uuid then 82-g*0.45
    when '20000000-0000-0000-0000-000000000003'::uuid then 64-g*1.00
    else 95-g*0.15
  end,
  case v.id
    when '20000000-0000-0000-0000-000000000001'::uuid then 95-g*0.12
    when '20000000-0000-0000-0000-000000000002'::uuid then 79-g*0.55
    when '20000000-0000-0000-0000-000000000003'::uuid then 58-g*0.80
    else 94-g*0.18
  end,
  case v.id when '20000000-0000-0000-0000-000000000003'::uuid then 83 else 94 end,
  greatest(30,v.battery_pct+(7-g)*0.5),
  case v.id
    when '20000000-0000-0000-0000-000000000001'::uuid then 68-g*0.8
    when '20000000-0000-0000-0000-000000000002'::uuid then 61-g*0.7
    when '20000000-0000-0000-0000-000000000003'::uuid then 52-g*0.6
    else 74-g*0.9
  end,
  case v.id when '20000000-0000-0000-0000-000000000003'::uuid then 92+g*0.7 else 82+g*0.3 end,
  case v.id when '20000000-0000-0000-0000-000000000003'::uuid then 69-g*0.7 else 90-g*0.2 end,
  case v.id when '20000000-0000-0000-0000-000000000003'::uuid then 31.8 else 34.2 end,
  case v.id when '20000000-0000-0000-0000-000000000003'::uuid then 82 else 97 end,
  'closed',
  case v.id
    when '20000000-0000-0000-0000-000000000001'::uuid then 3100
    when '20000000-0000-0000-0000-000000000002'::uuid then 1800
    when '20000000-0000-0000-0000-000000000003'::uuid then 620
    else 2600
  end,
  1180+g*4,
  now()-((7-g)*interval '20 minutes')
from public.vehicles v
cross join generate_series(0,7) g
where v.id in (
  '20000000-0000-0000-0000-000000000001',
  '20000000-0000-0000-0000-000000000002',
  '20000000-0000-0000-0000-000000000003',
  '20000000-0000-0000-0000-000000000004'
);

-- Operator actions included in chain-of-custody context.
delete from public.shipment_actions
where shipment_id in (
  '30000000-0000-0000-0000-000000000001',
  '30000000-0000-0000-0000-000000000002',
  '30000000-0000-0000-0000-000000000003',
  '30000000-0000-0000-0000-000000000004'
);
insert into public.shipment_actions (shipment_id,action,notes,actor,created_at) values
('30000000-0000-0000-0000-000000000001','RESET_MONITORING','Routine monitoring confirmed after checkpoint.','Control Tower',now()-interval '45 minutes'),
('30000000-0000-0000-0000-000000000002','PRIORITIZE','Cooling degradation detected; shipment elevated for closer monitoring.','Control Tower',now()-interval '50 minutes'),
('30000000-0000-0000-0000-000000000002','RESET_MONITORING','Cooling recovered; enhanced monitoring retained.','Neeraj Singh',now()-interval '12 minutes'),
('30000000-0000-0000-0000-000000000003','QUARANTINE','Critical excursion accepted; shipment held for quality review.','Control Tower',now()-interval '18 minutes'),
('30000000-0000-0000-0000-000000000004','PRIORITIZE','Emergency antivenom placed on accelerated handling path.','Emergency Desk',now()-interval '78 minutes');

-- Add richer alerts. Existing fixed IDs are updated instead of duplicated.
insert into public.alerts (
  id,shipment_id,vehicle_id,severity,alert_type,title,message,status,recommended_action,created_at
) values
('40000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000002','20000000-0000-0000-0000-000000000002','warning','cooling_failure','Cooling performance degraded','Supply air temperature rose toward the upper validated limit.','acknowledged','Continue enhanced monitoring and verify reefer compressor load.',now()-interval '52 minutes'),
('40000000-0000-0000-0000-000000000002','30000000-0000-0000-0000-000000000003','20000000-0000-0000-0000-000000000003','critical','critical_temperature_excursion','Critical cold-chain excursion','Product temperature exceeded target range and survival score is falling.','open','Maintain quarantine and escalate for trained quality review.',now()-interval '28 minutes'),
('40000000-0000-0000-0000-000000000003','30000000-0000-0000-0000-000000000003','20000000-0000-0000-0000-000000000003','warning','compressor_efficiency','Reefer compressor efficiency low','Compressor efficiency has fallen below the normal demo threshold.','open','Inspect reefer compressor and coolant system.',now()-interval '42 minutes'),
('40000000-0000-0000-0000-000000000004','30000000-0000-0000-0000-000000000004','20000000-0000-0000-0000-000000000004','info','priority_route','Priority route active','Emergency shipment is on accelerated route with receiving team pre-alerted.','open','Maintain expedited route and avoid unnecessary stops.',now()-interval '20 minutes')
on conflict (id) do update set
  severity=excluded.severity,
  alert_type=excluded.alert_type,
  title=excluded.title,
  message=excluded.message,
  status=excluded.status,
  recommended_action=excluded.recommended_action,
  created_at=excluded.created_at;

-- Ensure scenario names remain linked to the same four demo twins.
update public.scenarios set shipment_id='30000000-0000-0000-0000-000000000001' where scenario_key='healthy_delivery';
update public.scenarios set shipment_id='30000000-0000-0000-0000-000000000002' where scenario_key='recoverable_cooling_failure';
update public.scenarios set shipment_id='30000000-0000-0000-0000-000000000003' where scenario_key='critical_quarantine';
update public.scenarios set shipment_id='30000000-0000-0000-0000-000000000004' where scenario_key='priority_shipment';

-- Verification result: should return 4 shipments and dense supporting data.
select
  (select count(*) from public.shipments where id::text like '30000000-0000-0000-0000-00000000000%') as demo_shipments,
  (select count(*) from public.telemetry where shipment_id in (
    '30000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000002',
    '30000000-0000-0000-0000-000000000003','30000000-0000-0000-0000-000000000004')) as telemetry_points,
  (select count(*) from public.simulation_ticks where shipment_id in (
    '30000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000002',
    '30000000-0000-0000-0000-000000000003','30000000-0000-0000-0000-000000000004')) as risk_points,
  (select count(*) from public.custody_events) as custody_events,
  (select count(*) from public.driver_behavior_snapshots) as driver_snapshots,
  (select count(*) from public.vehicle_health_snapshots) as vehicle_health_snapshots;


-- ============================================================
-- LIVE ONLINE UPGRADE
-- ============================================================

-- ColdLife Twin — LIVE ONLINE BACKEND UPGRADE
-- Run AFTER the Full Demo Data SQL.
-- Adds continuously changing telemetry, fuel data, live risk history,
-- driver behaviour, vehicle health and an automatic 10-second Supabase Cron job.

create extension if not exists pgcrypto;
-- pg_cron is optional; see supabase/optional-cron.sql

-- -------------------------------------------------------------------
-- FUEL + LIVE VEHICLE FIELDS
-- -------------------------------------------------------------------

alter table public.vehicles
  add column if not exists fuel_level_pct numeric(6,2),
  add column if not exists fuel_consumption_lph numeric(7,2),
  add column if not exists odometer_km numeric(12,2),
  add column if not exists engine_temp_c numeric(6,2),
  add column if not exists reefer_power_pct numeric(6,2);

alter table public.telemetry
  add column if not exists fuel_level_pct numeric(6,2),
  add column if not exists fuel_consumption_lph numeric(7,2),
  add column if not exists engine_temp_c numeric(6,2),
  add column if not exists reefer_power_pct numeric(6,2),
  add column if not exists survival_score numeric(6,2);

-- -------------------------------------------------------------------
-- LIVE HISTORY TABLES
-- -------------------------------------------------------------------

create table if not exists public.risk_history (
  id bigint generated by default as identity primary key,
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  recorded_at timestamptz not null default now(),
  survival_score numeric(6,2) not null,
  risk_score numeric(6,2) not null,
  risk_level text not null
);

create index if not exists idx_risk_history_shipment_time
  on public.risk_history(shipment_id, recorded_at desc);

create table if not exists public.custody_events (
  id uuid primary key default gen_random_uuid(),
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  event_type text not null,
  title text not null,
  description text not null default '',
  location text,
  actor text,
  status text not null default 'complete',
  recorded_at timestamptz not null default now()
);

create index if not exists idx_custody_events_shipment_time
  on public.custody_events(shipment_id, recorded_at desc);

create table if not exists public.driver_behavior_snapshots (
  id bigint generated by default as identity primary key,
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  vehicle_id uuid references public.vehicles(id) on delete set null,
  driver_name text,
  style text not null default 'balanced',
  driver_score numeric(6,2) not null default 90,
  avg_speed_kmh numeric(7,2),
  max_speed_kmh numeric(7,2),
  harsh_braking_count integer not null default 0,
  harsh_accel_count integer not null default 0,
  cornering_count integer not null default 0,
  speeding_events integer not null default 0,
  idle_minutes numeric(7,2) not null default 0,
  fatigue_score numeric(6,2) not null default 10,
  eco_score numeric(6,2) not null default 90,
  recorded_at timestamptz not null default now()
);

create index if not exists idx_driver_behavior_shipment_time
  on public.driver_behavior_snapshots(shipment_id, recorded_at desc);

create table if not exists public.vehicle_health_snapshots (
  id bigint generated by default as identity primary key,
  vehicle_id uuid not null references public.vehicles(id) on delete cascade,
  overall_health_pct numeric(6,2) not null default 90,
  reefer_health_pct numeric(6,2) not null default 90,
  compressor_efficiency_pct numeric(6,2) not null default 90,
  battery_health_pct numeric(6,2) not null default 90,
  battery_pct numeric(6,2),
  fuel_pct numeric(6,2),
  fuel_consumption_lph numeric(7,2),
  engine_temp_c numeric(6,2),
  coolant_pct numeric(6,2),
  tyre_pressure_psi numeric(6,2),
  gps_signal_pct numeric(6,2),
  door_status text not null default 'closed',
  service_due_km integer not null default 2500,
  reefer_runtime_hours numeric(10,2) not null default 0,
  recorded_at timestamptz not null default now()
);

alter table public.vehicle_health_snapshots
  add column if not exists fuel_consumption_lph numeric(7,2);

create index if not exists idx_vehicle_health_vehicle_time
  on public.vehicle_health_snapshots(vehicle_id, recorded_at desc);

create table if not exists public.demo_live_state (
  shipment_id uuid primary key references public.shipments(id) on delete cascade,
  tick_no bigint not null default 0,
  updated_at timestamptz not null default now()
);

-- -------------------------------------------------------------------
-- INITIAL FUEL VALUES
-- -------------------------------------------------------------------

update public.vehicles
set
  fuel_level_pct = coalesce(fuel_level_pct,
    case code
      when 'CL-REEFER-01' then 86
      when 'CL-REEFER-02' then 78
      when 'CL-REEFER-03' then 69
      when 'CL-REEFER-04' then 91
      else 80
    end
  ),
  fuel_consumption_lph = coalesce(fuel_consumption_lph, 7.8),
  odometer_km = coalesce(odometer_km, 42000 + random() * 18000),
  engine_temp_c = coalesce(engine_temp_c, 84),
  reefer_power_pct = coalesce(reefer_power_pct, 72);

insert into public.demo_live_state(shipment_id, tick_no)
select id, 0
from public.shipments
where tracking_code in ('CLT-2401','CLT-2402','CLT-2403','CLT-2404')
on conflict (shipment_id) do nothing;

-- -------------------------------------------------------------------
-- ENSURE EACH DEMO SHIPMENT HAS BASE CUSTODY EVENTS
-- -------------------------------------------------------------------

insert into public.custody_events
  (shipment_id, event_type, title, description, actor, location, status, recorded_at)
select
  s.id,
  'handoff',
  'Shipment released to refrigerated vehicle',
  'Product loaded, seal checked and custody transferred to transport team.',
  coalesce(v.driver_name, 'ColdLife Driver'),
  'Origin cold hub',
  'complete',
  coalesce(s.started_at, now() - interval '90 minutes')
from public.shipments s
left join public.vehicles v on v.id = s.vehicle_id
where s.tracking_code in ('CLT-2401','CLT-2402','CLT-2403','CLT-2404')
  and not exists (
    select 1 from public.custody_events ce
    where ce.shipment_id = s.id
  );

-- -------------------------------------------------------------------
-- LIVE TICK FUNCTION
-- -------------------------------------------------------------------

create or replace function public.run_live_demo_tick()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  r record;
  v_tick bigint;
  v_phase integer;
  v_temp numeric;
  v_humidity numeric;
  v_survival numeric;
  v_risk text;
  v_risk_score numeric;
  v_speed numeric;
  v_battery numeric;
  v_fuel numeric;
  v_fuel_lph numeric;
  v_engine numeric;
  v_reefer numeric;
  v_lat double precision;
  v_lng double precision;
  v_driver_score numeric;
  v_eco numeric;
  v_overall numeric;
  v_reefer_health numeric;
  v_compressor numeric;
  v_door text;
begin
  for r in
    select
      s.*,
      v.code as vehicle_code,
      v.driver_name,
      v.battery_pct as vehicle_battery,
      v.speed_kmh as vehicle_speed,
      v.fuel_level_pct as vehicle_fuel,
      v.fuel_consumption_lph as vehicle_fuel_lph,
      v.odometer_km,
      v.id as joined_vehicle_id
    from public.shipments s
    join public.vehicles v on v.id = s.vehicle_id
    where s.tracking_code in ('CLT-2401','CLT-2402','CLT-2403','CLT-2404')
  loop
    insert into public.demo_live_state(shipment_id, tick_no, updated_at)
    values (r.id, 1, now())
    on conflict (shipment_id)
    do update set
      tick_no = public.demo_live_state.tick_no + 1,
      updated_at = now()
    returning tick_no into v_tick;

    v_phase := mod(v_tick, 36);

    -- Different live patterns give the four hackathon demo shipments
    -- visibly different graphs.
    if r.tracking_code = 'CLT-2401' then
      v_temp := 4.15 + 0.32 * sin(v_tick::double precision / 2.2);
      v_humidity := 57 + 2.5 * sin(v_tick::double precision / 3.1);
      v_survival := 98.2 - 0.7 * abs(sin(v_tick::double precision / 5.0));
      v_speed := 46 + 8 * sin(v_tick::double precision / 2.8);
      v_driver_score := 94;
      v_eco := 92;
      v_overall := 96;
      v_reefer_health := 97;
      v_compressor := 95;
    elsif r.tracking_code = 'CLT-2402' then
      if v_phase < 14 then
        v_temp := 4.7 + (v_phase * 0.36);
        v_survival := 94 - (v_phase * 1.35);
      elsif v_phase < 24 then
        v_temp := 9.7 - ((v_phase - 14) * 0.46);
        v_survival := 75.5 + ((v_phase - 14) * 1.35);
      else
        v_temp := 5.0 + 0.25 * sin(v_tick::double precision / 2.0);
        v_survival := 89 + 1.0 * sin(v_tick::double precision / 5.0);
      end if;
      v_humidity := 62 + 5 * sin(v_tick::double precision / 3.5);
      v_speed := 40 + 12 * sin(v_tick::double precision / 2.4);
      v_driver_score := 87;
      v_eco := 83;
      v_overall := 88;
      v_reefer_health := case when v_phase < 14 then 78 else 88 end;
      v_compressor := case when v_phase < 14 then 71 else 86 end;
    elsif r.tracking_code = 'CLT-2403' then
      v_temp := 10.4 + 1.25 * sin(v_tick::double precision / 2.6);
      v_humidity := 73 + 4 * sin(v_tick::double precision / 4.0);
      v_survival := greatest(38, 58 - (mod(v_tick, 25) * 0.65));
      v_speed := 28 + 8 * sin(v_tick::double precision / 2.9);
      v_driver_score := 76;
      v_eco := 71;
      v_overall := 68;
      v_reefer_health := 58;
      v_compressor := 54;
    else
      v_temp := 3.85 + 0.28 * sin(v_tick::double precision / 2.1);
      v_humidity := 54 + 2.2 * sin(v_tick::double precision / 4.2);
      v_survival := 96.5 - 0.9 * abs(sin(v_tick::double precision / 4.0));
      v_speed := 54 + 9 * sin(v_tick::double precision / 2.7);
      v_driver_score := 91;
      v_eco := 88;
      v_overall := 94;
      v_reefer_health := 95;
      v_compressor := 93;
    end if;

    v_risk :=
      case
        when v_survival < 60 or v_temp >= 10 then 'critical'
        when v_survival < 78 or v_temp > r.target_temp_max_c then 'high'
        when v_survival < 90 then 'medium'
        else 'low'
      end;

    v_risk_score :=
      case v_risk
        when 'critical' then greatest(82, 100 - v_survival)
        when 'high' then greatest(62, 100 - v_survival)
        when 'medium' then greatest(35, 100 - v_survival)
        else greatest(5, 100 - v_survival)
      end;

    v_battery := greatest(
      48,
      coalesce(r.vehicle_battery, 94) - 0.015 + (random() - 0.5) * 0.08
    );

    v_engine := 82 + (v_speed / 22.0) + (random() - 0.5) * 2.0;
    v_reefer := least(100, greatest(45, 60 + abs(v_temp - 4.5) * 6 + random() * 5));
    v_fuel_lph := greatest(4.5, 6.0 + (v_speed / 18.0) + (v_reefer / 45.0));
    v_fuel := coalesce(r.vehicle_fuel, 82) - greatest(0.008, v_fuel_lph / 3600.0 * 10.0 / 1.2);

    -- Auto-refuel in the simulated demo when fuel gets low so the online
    -- demo can keep running indefinitely.
    if v_fuel < 18 then
      v_fuel := 88 + random() * 5;
    end if;

    v_lat := coalesce(r.latitude, 28.60) + 0.00045 * sin(v_tick::double precision / 3.0);
    v_lng := coalesce(r.longitude, 77.20) + 0.00055 * cos(v_tick::double precision / 3.0);

    update public.shipments
    set
      current_temp_c = round(v_temp, 2),
      current_humidity_pct = round(v_humidity, 2),
      survival_score = round(v_survival, 2),
      risk_level = v_risk,
      latitude = v_lat,
      longitude = v_lng,
      status = case when v_risk = 'critical' then 'quarantined' else 'in_transit' end,
      recommendation =
        case
          when v_risk = 'critical'
            then 'Critical excursion: maintain quarantine and escalate for quality review.'
          when v_risk = 'high'
            then 'Cooling performance degraded: restore refrigeration and increase monitoring.'
          when v_risk = 'medium'
            then 'Watch closely: conditions are trending toward the configured limit.'
          else 'Conditions stable. Continue standard monitoring.'
        end
    where id = r.id;

    update public.vehicles
    set
      latitude = v_lat,
      longitude = v_lng,
      temperature_c = round(v_temp, 2),
      humidity_pct = round(v_humidity, 2),
      battery_pct = round(v_battery, 2),
      speed_kmh = round(v_speed, 2),
      fuel_level_pct = round(v_fuel, 2),
      fuel_consumption_lph = round(v_fuel_lph, 2),
      engine_temp_c = round(v_engine, 2),
      reefer_power_pct = round(v_reefer, 2),
      odometer_km = coalesce(odometer_km, 45000) + (v_speed * 10.0 / 3600.0),
      status = case when v_risk in ('critical','high') then 'alert' else 'in_transit' end
    where id = r.vehicle_id;

    insert into public.telemetry (
      shipment_id, vehicle_id, recorded_at,
      temperature_c, humidity_pct, latitude, longitude,
      battery_pct, speed_kmh, door_open,
      fuel_level_pct, fuel_consumption_lph, engine_temp_c,
      reefer_power_pct, survival_score
    ) values (
      r.id, r.vehicle_id, now(),
      round(v_temp,2), round(v_humidity,2), v_lat, v_lng,
      round(v_battery,2), round(v_speed,2), false,
      round(v_fuel,2), round(v_fuel_lph,2), round(v_engine,2),
      round(v_reefer,2), round(v_survival,2)
    );

    insert into public.risk_history (
      shipment_id, recorded_at, survival_score, risk_score, risk_level
    ) values (
      r.id, now(), round(v_survival,2), round(v_risk_score,2), v_risk
    );

    insert into public.driver_behavior_snapshots (
      shipment_id, vehicle_id, driver_name, style,
      driver_score, avg_speed_kmh, max_speed_kmh,
      harsh_braking_count, harsh_accel_count, cornering_count, speeding_events,
      idle_minutes, fatigue_score, eco_score, recorded_at
    ) values (
      r.id, r.vehicle_id, coalesce(r.driver_name, 'ColdLife Driver'),
      case
        when v_driver_score >= 92 then 'smooth'
        when v_driver_score >= 85 then 'balanced'
        else 'aggressive'
      end,
      v_driver_score + (random() - 0.5) * 2,
      greatest(20, v_speed - 4),
      v_speed + 8 + random() * 5,
      case when random() > 0.86 then 1 else 0 end,
      case when random() > 0.88 then 1 else 0 end,
      case when random() > 0.90 then 1 else 0 end,
      case when v_speed > 58 and random() > 0.70 then 1 else 0 end,
      round((random() * 2.2)::numeric, 2),
      greatest(20, 100 - v_driver_score + random() * 8),
      v_eco + (random() - 0.5) * 3,
      now()
    );

    v_door := case when mod(v_tick, 47) = 0 then 'open' else 'closed' end;

    insert into public.vehicle_health_snapshots (
      vehicle_id,
      overall_health_pct, reefer_health_pct, compressor_efficiency_pct, battery_health_pct,
      battery_pct, fuel_pct, fuel_consumption_lph, engine_temp_c, coolant_pct,
      tyre_pressure_psi, gps_signal_pct, door_status, service_due_km,
      reefer_runtime_hours, recorded_at
    ) values (
      r.vehicle_id,
      v_overall + (random() - 0.5) * 2,
      v_reefer_health + (random() - 0.5) * 2,
      v_compressor + (random() - 0.5) * 2,
      v_battery,
      v_battery,
      v_fuel,
      v_fuel_lph,
      v_engine,
      91 + (random() - 0.5) * 3,
      34.5 + (random() - 0.5) * 1.2,
      97 + (random() - 0.5) * 2,
      v_door,
      greatest(400, 3200 - (mod(v_tick, 120) * 8)),
      coalesce(r.odometer_km, 45000) / 40.0,
      now()
    );

    -- Periodic custody milestones make the custody timeline keep changing too.
    if mod(v_tick, 18) = 0 then
      insert into public.custody_events (
        shipment_id, event_type, title, description,
        actor, location, status, recorded_at
      ) values (
        r.id,
        'checkpoint',
        'Live route checkpoint verified',
        'Telemetry verified: ' ||
        round(v_temp, 1)::text || '°C, survival ' ||
        round(v_survival, 0)::text || '%, fuel ' ||
        round(v_fuel, 0)::text || '%.',
        coalesce(r.driver_name, 'ColdLife Driver'),
        'Live GPS checkpoint',
        'active',
        now()
      );
    end if;

    -- Bound history size so a long-running demo does not grow forever.
    delete from public.telemetry
      where id in (
        select id from public.telemetry
        where shipment_id = r.id
        order by recorded_at desc
        offset 360
      );

    delete from public.risk_history
      where id in (
        select id from public.risk_history
        where shipment_id = r.id
        order by recorded_at desc
        offset 360
      );

    delete from public.driver_behavior_snapshots
      where id in (
        select id from public.driver_behavior_snapshots
        where shipment_id = r.id
        order by recorded_at desc
        offset 120
      );

    delete from public.vehicle_health_snapshots
      where id in (
        select id from public.vehicle_health_snapshots
        where vehicle_id = r.vehicle_id
        order by recorded_at desc
        offset 120
      );

    delete from public.custody_events
      where id in (
        select id from public.custody_events
        where shipment_id = r.id
        order by recorded_at desc
        offset 60
      );
  end loop;

  return jsonb_build_object(
    'ok', true,
    'updated_at', now(),
    'message', 'ColdLife live demo tick completed'
  );
end;
$$;

-- Manual reset helper.
create or replace function public.reset_live_demo()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.demo_live_state set tick_no = 0, updated_at = now();

  update public.vehicles
  set
    fuel_level_pct = case code
      when 'CL-REEFER-01' then 86
      when 'CL-REEFER-02' then 78
      when 'CL-REEFER-03' then 69
      when 'CL-REEFER-04' then 91
      else 80
    end,
    battery_pct = 94,
    fuel_consumption_lph = 7.5
  where code in ('CL-REEFER-01','CL-REEFER-02','CL-REEFER-03','CL-REEFER-04');

  perform public.run_live_demo_tick();

  return jsonb_build_object('ok', true, 'message', 'Live demo reset');
end;
$$;

-- -------------------------------------------------------------------
-- SECURITY FOR HACKATHON DEMO
-- -------------------------------------------------------------------

alter table public.risk_history enable row level security;
alter table public.custody_events enable row level security;
alter table public.driver_behavior_snapshots enable row level security;
alter table public.vehicle_health_snapshots enable row level security;
alter table public.demo_live_state enable row level security;

drop policy if exists "public read risk history" on public.risk_history;
create policy "public read risk history"
on public.risk_history for select
to anon, authenticated
using (true);

drop policy if exists "public read custody events" on public.custody_events;
create policy "public read custody events"
on public.custody_events for select
to anon, authenticated
using (true);

drop policy if exists "public read driver behavior" on public.driver_behavior_snapshots;
create policy "public read driver behavior"
on public.driver_behavior_snapshots for select
to anon, authenticated
using (true);

drop policy if exists "public read vehicle health" on public.vehicle_health_snapshots;
create policy "public read vehicle health"
on public.vehicle_health_snapshots for select
to anon, authenticated
using (true);

drop policy if exists "public read demo live state" on public.demo_live_state;
create policy "public read demo live state"
on public.demo_live_state for select
to anon, authenticated
using (true);

grant select on public.risk_history to anon, authenticated;
grant select on public.custody_events to anon, authenticated;
grant select on public.driver_behavior_snapshots to anon, authenticated;
grant select on public.vehicle_health_snapshots to anon, authenticated;
grant select on public.demo_live_state to anon, authenticated;

grant execute on function public.run_live_demo_tick() to anon, authenticated;
grant execute on function public.reset_live_demo() to anon, authenticated;

-- -------------------------------------------------------------------
-- REALTIME
-- -------------------------------------------------------------------

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='risk_history'
  ) then
    alter publication supabase_realtime add table public.risk_history;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='driver_behavior_snapshots'
  ) then
    alter publication supabase_realtime add table public.driver_behavior_snapshots;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='vehicle_health_snapshots'
  ) then
    alter publication supabase_realtime add table public.vehicle_health_snapshots;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='custody_events'
  ) then
    alter publication supabase_realtime add table public.custody_events;
  end if;
end $$;

-- -------------------------------------------------------------------
-- LIVE TICK
-- -------------------------------------------------------------------
-- The web app calls public.run_live_demo_tick() periodically for the demo.
-- This keeps the main schema deployable without requiring the optional pg_cron extension.
select public.run_live_demo_tick();

-- Basic verification (cron-independent).
select
  (select count(*) from public.shipments where tracking_code like 'CLT-240%') as demo_shipments,
  (select count(*) from public.telemetry where shipment_id in (
    select id from public.shipments where tracking_code like 'CLT-240%'
  )) as telemetry_points,
  (select count(*) from public.risk_history) as live_risk_points,
  (select count(*) from public.driver_behavior_snapshots) as driver_snapshots,
  (select count(*) from public.vehicle_health_snapshots) as health_snapshots,
  (select count(*) from public.custody_events) as custody_events;

-- FINAL CRITICAL DEMO FIX
-- ColdLife Twin — ensure there is one undeniable critical demo shipment.
-- Gemini is not involved.

update public.shipments
set
  status = 'quarantined',
  priority = 'critical',
  risk_level = 'critical',
  current_temp_c = target_temp_max_c + 2.5,
  survival_score = 49,
  recommendation = 'CRITICAL: cold-chain excursion. Quarantine and boost cooling immediately.'
where tracking_code in ('CLT-2403','CLT-1003');

select
  tracking_code,
  status,
  risk_level,
  current_temp_c,
  target_temp_max_c,
  survival_score
from public.shipments
where tracking_code in ('CLT-2403','CLT-1003');

